name: corsac_dal
version: 0.1.0-dev
description: Database Abstraction Layer based on Repository pattern.
homepage: https://github.com/corsac-dart/dal
author: Anatoly Pulyaevskiy

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  quiver: '>=0.22.0 <0.23.0'

dev_dependencies:
  test: "^0.12.6+1"
  corsac_di:
    git: https://github.com/corsac-dart/di.git
  dart_coveralls: "^0.4.0"
