name: corsac_stateless
version: 0.1.0-dev
description: Experimental Repository layer for applications
homepage: https://github.com/corsac-dart/stateless
author: Anatoly Pulyaevskiy

environment:
  sdk: '>=1.9.0 <2.0.0'

dev_dependencies:
  test: "^0.12.6+1"
